### ISSUE TITLE
Error while converting RWD to txt

### ISSUE THREAD

**Issue by kenneth46k** [nrgpy/nrgpy#9] opened 2020-05-12 23:34 UTC
SDR test OK!
Time elapsed: 0 s | 1 / 1 [=============================================] 100%	Traceback (most recent call last):
  File "C:\Users\kenneth\AppData\Local\Continuum\Anaconda3\lib\site-packages\nrgpy\convert_rwd.py", line 294, in _copy_txt_file
    shutil.copy(txt_file_path, out_path)
  File "C:\Users\kenneth\AppData\Local\Continuum\Anaconda3\lib\shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\kenneth\AppData\Local\Continuum\Anaconda3\lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\NRG\\ScaledData\\\\018720120120200.txt'

Unable to copy 018720120120200.txt to ScaledData\

RWDs in    : 1
TXTs out   : 0
LOGs out   : 0
----------------
Difference : 1

**Comment by dave-c-vt** [comment] 2020-05-12 23:55
hi kenneth, can you please include the command you ran, just as you ran it?

**Comment by kenneth46k** [comment] 2020-05-13 08:34
I used below code,

from nrgpy.convert_rwd import local
file_filter = '0187201201202' # for Feb 2019 files from site 0434
rwd_directory = 'C:/Users/kenneth/rwd/'
out_directory = 'C:/Users/kenneth/txt/'


converter = local(file_filter=file_filter, rwd_dir=rwd_directory, out_dir=out_directory)
converter.convert()

**Comment by dave-c-vt** [comment] 2020-05-14 12:26
ok, thanks. it appears to be broken; i'll take a look and let you know!

**Comment by dave-c-vt** [comment] 2020-05-14 20:28
something got toasted along the way. i'll dig in to find the cause and release soon. in the meantime, you can remove nrgpy and install

nrgpy==0.10.1

and you should be able to convert the rwds for now

**Comment by dave-c-vt** [comment] 2020-05-15 00:07
@kenneth46k i think we've got it!

please upgrade to nrgpy 0.12.6 and try again.

**Comment by nrgpy** [comment] 2020-05-21 16:32
closed.

**Comment by kenneth46k** [comment] 2021-06-08 21:43
Hi, even after updating to the said version 0.12.6 or higher, this issue is still there for rwd conversion.

SDR test OK!
Time elapsed: 0 s | 1 / 1 [=============================================] 100%	Traceback (most recent call last):
  File "C:\Users\kenneth\AppData\Local\Continuum\Anaconda3\lib\site-packages\nrgpy\convert_rwd.py", line 294, in _copy_txt_file
    out_path = self.file_path_joiner.join([self.out_dir,txt_file_name])
  File "C:\Users\kvjhj\AppData\Local\Continuum\Anaconda3\lib\shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\kvjhj\AppData\Local\Continuum\Anaconda3\lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\NRG\\ScaledData\\\\018720120120200.txt'

Unable to copy 018720120120200.txt to C:\Users\kvjhj\txt\

RWDs in    : 1
TXTs out   : 0
LOGs out   : 0
----------------
Difference : 1

**Comment by dave-c-vt** [comment] 2021-06-09 12:44
hi kenneth46k!

can you paste in the script that you're running?

for example, when i run:

```import nrgpy
rwd_directory = r'C:\Users\drc\data\symclassic\raw\0434'
out_directory = r'C:\Users\drc\data\symclassic\txt\0434'
site_filter = '' 
encryption_pass = '' 
use_site_file = False

converter = nrgpy.convert.convert_rwd.local(
                  rwd_dir=rwd_directory,
                  out_dir=out_directory, 
                  encryption_pin=encryption_pass, 
                  use_site_file=use_site_file,
                  site_filter=site_filter
            )

converter.convert()

```

i get

```Time elapsed: 97 s | 477 / 477 [=============================================] 100%	

RWDs in    : 477
TXTs out   : 477
LOGs out   : 0
----------------
Difference : 0```

**Comment by kenneth46k** [comment] 2021-06-10 15:05
I tried to execute ur same script with my folder path as given below,

import nrgpy

rwd_directory = r'C:\Users\kvjhj\rwd'
out_directory = r'C:\Users\kvjhj\txt'
site_filter = '' 
encryption_pass = '' 
use_site_file = False

converter = nrgpy.convert.convert_rwd.local(
                  rwd_dir=rwd_directory,
                  out_dir=out_directory, 
                  encryption_pin=encryption_pass, 
                  use_site_file=use_site_file,
                  site_filter=site_filter
            )

converter.convert()

Again it showed same error.
Time elapsed: 0 s | 1 / 4 [===========                                  ] 25%	Traceback (most recent call last):
  File "C:\Users\kvjhj\AppData\Local\Programs\Python\Python37\lib\site-packages\nrgpy\convert\convert_rwd.py", line 297, in _copy_txt_file
    shutil.copy(txt_file_path, out_path)
  File "C:\Users\kvjhj\AppData\Local\Programs\Python\Python37\lib\shutil.py", line 248, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\kvjhj\AppData\Local\Programs\Python\Python37\lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\NRG\\ScaledData\\018720120121201.txt'

Unable to copy 018720120121201.txt to C:\Users\kvjhj\txt\
Time elapsed: 8 s | 2 / 4 [======================                       ] 50%	Traceback (most recent call last):
  File "C:\Users\kvjhj\AppData\Local\Programs\Python\Python37\lib\site-packages\nrgpy\convert\convert_rwd.py", line 297, in _copy_txt_file
    shutil.copy(txt_file_path, out_path)
  File "C:\Users\kvjhj\AppData\Local\Programs\Python\Python37\lib\shutil.py", line 248, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\kvjhj\AppData\Local\Programs\Python\Python37\lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\NRG\\ScaledData\\018720120122202.txt'

Unable to copy 018720120122202.txt to C:\Users\kvjhj\txt\
Time elapsed: 11 s | 3 / 4 [=================================            ] 75%	Traceback (most recent call last):
  File "C:\Users\kvjhj\AppData\Local\Programs\Python\Python37\lib\site-packages\nrgpy\convert\convert_rwd.py", line 297, in _copy_txt_file
    shutil.copy(txt_file_path, out_path)
  File "C:\Users\kvjhj\AppData\Local\Programs\Python\Python37\lib\shutil.py", line 248, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\kvjhj\AppData\Local\Programs\Python\Python37\lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\NRG\\ScaledData\\018720120123203.txt'

Unable to copy 018720120123203.txt to C:\Users\kvjhj\txt\
Time elapsed: 13 s | 4 / 4 [=============================================] 100%	Traceback (most recent call last):
  File "C:\Users\kvjhj\AppData\Local\Programs\Python\Python37\lib\site-packages\nrgpy\convert\convert_rwd.py", line 297, in _copy_txt_file
    shutil.copy(txt_file_path, out_path)
  File "C:\Users\kvjhj\AppData\Local\Programs\Python\Python37\lib\shutil.py", line 248, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\kvjhj\AppData\Local\Programs\Python\Python37\lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\NRG\\ScaledData\\018720120124204.txt'

Unable to copy 018720120124204.txt to C:\Users\kvjhj\txt\


RWDs in    : 4
TXTs out   : 0
LOGs out   : 0
----------------
Difference : 4

**Comment by kenneth46k** [comment] 2021-06-10 18:35
Is there anything to do with my NRG path. No txt files created in this folder C:\NRG\ScaledData\.

**Comment by dave-c-vt** [comment] 2021-06-11 02:12
maybe?

you could try removing the bit of code that deletes to text files to see if they remain in the C:\NRG\ScaledData folder.

in 

`C:\Users\kvjhj\AppData\Local\Programs\Python\Python37\lib\site-packages\nrgpy\convert\convert_rwd.py`

comment out the last try/except in the file (line 296 onward):

```
        try:
            shutil.copy(txt_file_path, out_path)

            try:
                os.remove(txt_file_path)
            except:
                print("{0} remains in {1}".format(txt_file_name, self.ScaledData))

        except:
            import traceback
            print(traceback.format_exc())
            print("Unable to copy {0} to {1}".format(txt_file_name,self.out_dir))
```

**Comment by kenneth46k** [comment] 2021-06-11 08:41
Sorry Dave. there was something wrong in my end. Your above solution also didn't worked. Then I tried to check the version of SDR. It was 7.01. Then i updated it to latest 7.08.18. Then everything works fine. Thanks

**Comment by dave-c-vt** [comment] 2021-06-11 13:04
ok, good to know it's working and how you fixed it!

**Comment by abohara** [comment] 2022-04-18 23:07
@dave-c-vt Request to re-open and fix this. This error will re-occur if the the `rwd_dir` is missing a trailing slash at the end.

The issue is line 278 in `convert/convert_rwd.py`. There is a string join as opposed to an `os.path.join` which means if the trailing slash is missing then the file will not copy over and the error fails silently creating the above error. 

![image](https://user-images.githubusercontent.com/6306857/163890797-7227dfcf-f71c-46f1-9554-1dfdc4b1fd49.png)

Line 277 seems to have the solution but is commented out.

**Comment by dave-c-vt** [comment] 2022-04-19 00:47
@abohara ok, will take a look. thanks.

**Comment by dave-c-vt** [comment] 2022-04-22 20:31
issue addressed in PR 33 https://github.com/nrgpy/nrgpy/pull/33

will close issue 9 when nrgpy v1.5.3 pushed to pypi

**Comment by dave-c-vt** [comment] 2022-04-22 20:41
new version posted

`pip install --upgrade nrgpy`

**Closed** 2022-04-22 20:41 UTC
Labels: bug

**Comment by abohara** [comment] 2022-04-27 21:25
Thank you @dave-c-vt
